pipeline {
    agent any

    environment {
        APP_DIR = 'messaging_app'
        GITHUB_REPO = 'https://github.com/SRYVarder/alx-backend-python.git'
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: "${GITHUB_REPO}", credentialsId: 'github-creds'
            }
        }

        stage('Set Up Python Environment') {
            steps {
                script {
                    sh '''
                    python3 -m venv venv
                    . venv/bin/activate
                    pip3 install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    sh '''
                    . venv/bin/activate
                    pytest messaging_app --maxfail=1 --disable-warnings -q --junitxml=messaging_app/test-results.xml
                    '''
                }
            }
            post {
                always {
                    junit 'messaging_app/test-results.xml'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh '''
                    docker build -t messaging_app:latest ${APP_DIR}
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            environment {
                DOCKER_HUB = credentials('dockerhub-creds')
            }
            steps {
                script {
                    sh '''
                    echo $DOCKER_HUB_PSW | docker login -u $DOCKER_HUB_USR --password-stdin
                    docker tag messaging_app:latest $DOCKER_HUB_USR/messaging_app:latest
                    docker push $DOCKER_HUB_USR/messaging_app:latest
                    '''
                }
            }
        }
    }
}
