pipeline {
    agent any

    environment {
        GITHUB_REPO = 'https://github.com/SRYVarder/alx-backend-python.git'
        APP_DIR = 'messaging_app'
        DOCKER_HUB_CREDENTIALS = credentials('dockerhub-creds')
    }

    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: "${GITHUB_REPO}"
            }
        }

        stage('Set Up Python Environment') {
            steps {
                script {
                    sh '''
                    cd ${APP_DIR}
                    python3 -m venv venv
                    . venv/bin/activate
                    pip install -r requirements.txt
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                script {
                    sh '''
                    cd ${APP_DIR}
                    . venv/bin/activate
                    pytest --maxfail=1 --disable-warnings -q --junitxml=test-results.xml
                    '''
                }
            }
            post {
                always {
                    junit 'messaging_app/test-results.xml'
                }
            }
        }

        stage('Build Docker Image') {
            steps {
                script {
                    sh '''
                    cd ${APP_DIR}
                    docker build -t $DOCKER_HUB_CREDENTIALS_USR/messaging_app:latest .
                    '''
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                script {
                    sh '''
                    echo $DOCKER_HUB_CREDENTIALS_PSW | docker login -u $DOCKER_HUB_CREDENTIALS_USR --password-stdin
                    docker push $DOCKER_HUB_CREDENTIALS_USR/messaging_app:latest
                    '''
                }
            }
        }
    }
}
