apiVersion: v1
kind: Service
metadata:
  name: messaging-app-switch
spec:
  selector:
    app: messaging-app
    # initially point to blue
    version: blue
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
